### ISSUE TITLE
App crashing when deleting Category

### ISSUE THREAD

**Issue by tsilvius** [jabstone/JABtalk#5]
When deleting a category in Admin mode, the app crashes.
used Device: Samsung Galaxy S7
used Android version: 8.0.0

**Comment by jabstone** [comment]
Having a really hard time reproducing this. Does this happen after restoring a backup? I've tried deleting dozens of categories but am unable to repro. Are you able to repro consistently? If yes, can you let me know exactly what steps you're doing to delete the category. For example, are there nested sub-categories, etc...  If yes, at what level is the category you're trying to delete. Appreciate the help and bug report.

**Comment by tsilvius** [comment]
Hi,Thank you for your response. When deleting a category, I tried this right after creation. It does not seem to be related to restoration of a back-up The category itself is empty. Trying this on a mobile phone right now, but will also test on other device.

**Comment by tsilvius** [comment]
Ow forgot to mention: category is in top level, in management: press and hold category and choose delete, and confirm choice when asked if i'm sure. This is 100% reproducable.

**Comment by jabstone** [comment]
This may have inadvertently been fixed in a new build. Unable to repro. If still an issue, please reopen.
