### ISSUE TITLE
App failing on Audio synth. when importing on other device

### ISSUE THREAD

**Issue by tsilvius** [jabstone/JABtalk#6]
Created categories and words using synth audio.  made a back-up and imported on other device.  When tapping category or word, app freezes until rotation of the tablet or phone.  When disabling synth audio ore using recorded audio the  app works.

Created : Samsung Galaxy S7
Tried import: Samsung Galaxy tab 3 and galaxy A8

**Comment by tsilvius** [comment]
Hi all,

Found that switching from Samsung text to speech engine to Google text to speech engine did the job. As a feature request i would like to have the option to use orher engines.

Thank you

**Comment by jabstone** [comment]
Cleaning up old issues. Thanks for the suggestion. Closing since JABtalk doesn't set the speech engine. User's can use whatever speech engine they choose via system settings.
